### ISSUE TITLE
ubuntu 20.04

### ISSUE THREAD

**Issue by rezarastak** [teeks99/clang-ubuntu-docker#1]
Thanks for your great work @teeks99. I have been using your docker images as the base image for some of my projects. When are you planning to build the images on ubuntu 20.04 (focal) instead of 18.04?

**Comment by teeks99** [comment]
Yeah, that's been my plan for a while, I just need to find a few minutes to do it. The plan is to move clang-11 and clang-12 to focal.

**Comment by teeks99** [comment]
I pushed the update this morning, looks like they are live on dockerhub now.

**Comment by rezarastak** [comment]
Thank you so much @teeks99. The new docker image with ubuntu focal works perfectly with my workflow.
