### ISSUE TITLE
libunwind-XX-dev missing on Clang 12+?

### ISSUE THREAD

**Issue by offa** [teeks99/clang-ubuntu-docker#17]
The images do not include `libunwind-XX-dev` which might be needed if libc++ is used.

According to [docs](https://apt.llvm.org/) it can be installed using `apt-get`:

```
# libunwind
apt-get install libunwind-15-dev
```

##### Context:

Using libc++ clang doesn't pass the CMake compiler check:

```
/usr/bin/clang++-12 -stdlib=libc++   -m64 -stdlib=libc++  -m64  CMakeFiles/cmTC_d6423.dir/testCXXCompiler.cxx.o -o cmTC_d6423 
/usr/bin/ld: cannot find -lunwind
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by offa** [comment]
Clang 14+ may need `libclang-rt-XX-dev`.

**Comment by teeks99** [comment]
I have new images including this for clang 16+. It didn't immediately work for prior versions, but I'll try to play around a bit more.

**Comment by teeks99** [comment]
So 16 and 17 have a bunch of the related tools, I couldn't get them all earlier, but I did add libunwind to 15. Nothing for 14 or earlier.
