### ISSUE TITLE
Clang 15 / 16 are linux/arm64/v8 only now

### ISSUE THREAD

**Issue by offa** [teeks99/clang-ubuntu-docker#5]
Clang 15 and 16 do no longer work eg. on Github Action, since these tags are _linux/arm64/v8_ now. Earlier Clang versions are fine.

```
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
```
Failing the build a few steps later.

##### Example: 

While images up to _15_20220920_1115_ are still *linux/amd64*, _15_20220920_1220_ / _15_ switched to _linux/arm64/v8_. Similar for Clang 16. Version are taken from Dockerhub.

**Comment by teeks99** [comment]
That was my mistake, I'm trying to support both amd64 and arm64...apparently I need to use the manifest command to get that to work. A bit tricky when they both run (at different times) on different machines.

**Comment by teeks99** [comment]
I've updated it now, hopefully multiarch is working correctly and you'll get the right thing for the right machine! I'll need to think about a better way to automate this.

**Comment by offa** [comment]
Thanks, the images work again! :-)
